name: comcha-tutorial-globalfits
dependencies:
  - python = 3.12
  - numpy
  - scipy
  - pandas
  - matplotlib
  - xgboost
  - shap
  - optuna
  - scikit-learn
  - tl2cgen
  - treelite
  - ipykernel
  - emcee
  - corner
  - supertree
  - tensorflow==2.18.0
  - tf-keras
  - setuptools==81.0.0
  - gpflow
  - pip
  - pip:
    - alpaca-alps==1.2rc1
    - git+https://github.com/mmschlk/shapiq.git